CREATE DATABASE EMP_DB
USE EMP_DB
CREATE TABLE EMP_TABLE(emp_id int,emp_name varchar(100),dept varchar(100),designation varchar(100),salary bigint,hire_data Date)
INSERT INTO EMP_TABLE VALUES (1,'HANEESHA','MARKETING','SENIOR',50000,'11-7-2023')
INSERT INTO EMP_TABLE VALUES (2,'SHAHID','HR','JUNIOR',45000,'1-8-2024')
INSERT INTO EMP_TABLE VALUES (3,'SHEMEEM','FINANCE','SENIOR',60000,'5-3-2023')
INSERT INTO EMP_TABLE VALUES (4,'AJMAL','MARKETING','JUNIOR',30000,'7-3-2023')
INSERT INTO EMP_TABLE VALUES (5,'HANEE','IT','JUNIOR',50000,'11-7-2023')
SELECT * FROM EMP_TABLE
DELETE FROM EMP_TABLE

--1
SELECT salary FROM EMP_TABLE ORDER BY salary DESC
--2
SELECT dept, MAX(salary) AS max_salary from EMP_TABLE GROUP BY dept;
--3
SELECT MIN(salary) AS min_salary FROM EMP_TABLE;
--4
SELECT emp_name FROM EMP_TABLE WHERE designation = 'SENIOR' 
--5 
SELECT DISTINCT salary FROM EMP_TABLE ORDER BY salary DESC 
--6
SELECT (
    (SELECT MAX(salary) FROM EMP_TABLE WHERE dept = 'MARKETING') -
    (SELECT MAX(salary) FROM EMP_TABLE WHERE dept = 'HR')
) AS salary_difference;

--7
SELECT salary
FROM EMP_TABLE
WHERE dept = 'MARKETING'

--8
SELECT designation, COUNT(*) AS total_persons
FROM EMP_TABLE
GROUP BY designation;

--9
SELECT MAX(salary) AS highest_salary
FROM EMP_TABLE
WHERE dept = (
    SELECT dept
    FROM EMP_TABLE
    WHERE emp_name = 'AJMAL'
);
