namespace DomainDAL.Enums
{
    public enum JobInterviewStatus
    {
        SCHEDULED, ACCEPTED_BY_JOB_SEEKER, INTERVIEW_CONDUCTED, RESCHEDULED, REJECTED_BY_JOB_SEEKER, CANCELLED_BY_EMPLOYER
    
    }
}
